// <auto-generated />
namespace OnBoarding.EntityContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initial_Migrtaion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial_Migrtaion));
        
        string IMigrationMetadata.Id
        {
            get { return "201812261112284_Initial_Migrtaion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
